dist: precise
language: python
sudo: false
python:
  - "2.7"
env:
  - TOXENV="py27-dj18-sqlite"
  - TOXENV="py27-dj18-postgres"
  - TOXENV="py27-dj18-mysql"
  - TOXENV="py27-dj18-postgres_tz"
  - TOXENV="py27-dj18-mysql_tz"
  - TOXENV="py27-dj18-sqlite_tz"
  - TOXENV="py27-dj18-mysql_tz_nopytz"
  - TOXENV="py27-dj18-postgres_tz_nopytz"
  - TOXENV="py27-dj18-sqlite_tz_nopytz"

  - TOXENV="py27-dj110-sqlite"
  - TOXENV="py27-dj110-postgres"
  - TOXENV="py27-dj110-mysql"
  - TOXENV="py27-dj110-postgres_tz"
  - TOXENV="py27-dj110-mysql_tz"
  - TOXENV="py27-dj110-sqlite_tz"
  - TOXENV="py27-dj110-mysql_tz_nopytz"
  - TOXENV="py27-dj110-postgres_tz_nopytz"
  - TOXENV="py27-dj110-sqlite_tz_nopytz"

  - TOXENV="py27-dj111-sqlite"
  - TOXENV="py27-dj111-postgres"
  - TOXENV="py27-dj111-mysql"
  - TOXENV="py27-dj111-postgres_tz"
  - TOXENV="py27-dj111-mysql_tz"
  - TOXENV="py27-dj111-sqlite_tz"
  - TOXENV="py27-dj111-mysql_tz_nopytz"
  - TOXENV="py27-dj111-postgres_tz_nopytz"
  - TOXENV="py27-dj111-sqlite_tz_nopytz"

  - TOXENV="py34-dj111-sqlite"
  - TOXENV="py34-dj111-postgres"
  - TOXENV="py34-dj111-mysql"
  - TOXENV="py34-dj111-postgres_tz"
  - TOXENV="py34-dj111-mysql_tz"
  - TOXENV="py34-dj111-sqlite_tz"
  - TOXENV="py34-dj111-mysql_tz_nopytz"
  - TOXENV="py34-dj111-postgres_tz_nopytz"
  - TOXENV="py34-dj111-sqlite_tz_nopytz"
install: pip install tox
script: tox -e $TOXENV
before_script:
  - mysql -e 'create database qsstats_test;'
  - psql -c 'create database qsstats_test;' -U postgres
