dist: xenial
sudo: false
language: python
services:
  - mysql
  - postgresql
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
install: pip install tox-travis
script: tox
before_script:
  - mysql -e 'create database qsstats_test;'
  - psql -c 'create database qsstats_test;' -U postgres
